name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eca05d57cdf6ff0cd1962febfc2f91075e4aa8374669345c53461ca42a3616b2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
