name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "691345e7b5f79c690649668425ff889d2a890b94e2a9ac6e5ebeba6c8c908ec5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.142"
