name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3286ab5c04bf573a69aaae41343da0e9198e7d374c54a17731c0efb2c6294742"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.142"
