name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5e9aa2fb8e740e0efefa65710d8d6a5dd39f9526a9896b4cd2d3a9f9aa9a3c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
