name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "209d68f03ff70eb0ab4025fb6939696aa2ceb9920d217e3929ca8d72ca42739e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"
