name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce0f0505757b8b5a9155e4e575bdadd4c8eb1f31db183f29ce9b545842fe853f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.167"
