name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e95f11278ae45a06bc17c260bc6df7c37d5e77bcc6376fdc2aa54ee792a89b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
