name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71b902ddf6cb5856b97c43457cfc4b9cbd0fe744f5a72b18901ceb48a3b290b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
