name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47ac004632e0c54c49fad5755ed6d232ce14b8ffce452d90e49e67505ccd734f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
