name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9946b7705008d81ff944cddba02b970d29d08c2887f5a75575bbbd4878f1b24"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
