name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3f6509cc1e5856d895f99be9abe4e2d6ea89483dd35dcb5706679699f920e2d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
