name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "014740f3acfdce34bc140d20d3cf8921accb46c469695ca996b9ad1fc818a47c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.146"
