name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef69cdaeb9ffedfdb242f91108ea76ae1998923a4bd79b1eca770ee8f5a73e51"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
