name = "caneva20's 1.21"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d95010751203f298efe0e35b4fe61dbd2a6da61ef53278d2b937d766b27fb6ad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.154"
