name = "caneva20 SMP S2"
author = "caneva20"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d6f3af04567682e4ca9632c8447975b13ef97d09a17ab90334780df4f816ae8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
